#!/bin/bash

# Trap ctrl-c and call ctrl_c()
trap ctrl_c INT

function ctrl_c() {
	clear
}

for i in 'seq 1 5'; do
	sleep 1
	echo -n "."
done
# Animated Spinner 
spinner() {
     local pid=$1
     local delay=0.75
     local spinstr='|/-\'
     while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
	local temp=${spinstr#?}
	printf " [%c] " "$spinstr"
	local spinstr=$temp${spinstr%"$temp"}
	sleep $delay
	printf "\b\b\b\b\b\b"
     done
     printf "   \b\b\b\b"
}
# Here we clear the screen and set the currsor to invisible 
clear

tput civis
# Next we create the background art for the border of the stream
background() {
echo '

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////// The Alex Jones Show ////////////////////






































//////////// PRESS CTRL+C TO END TRANSMISSION //////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////'
printf "https://steemit.com/@xsmith      "  # I put this there you can put what ever you want ...
}

# Finally we draw the background, use omxplayer to display the stream and deploy the spinner!

background & omxplayer --win "0 100 1024 640"  -o local https://infowarslive-lh.akamaihd.net/i/infowarslivestream_1@353459/master.m3u8 2>/dev/null 1>&2 & spinner $!

# After that we reset the cursor to normal

tput cnorm


